### ISSUE TITLE
Streams API in spec is wrong - don't implement

### ISSUE THREAD

**Issue by msporny** [trustbloc/edv#101]
Hey folks, just a heads up that that Streams API in the EDV spec is wrong, please don't implement it. We need to update it to the newest thinking on large file support. Please monitor the DIF SDS WG for details on that.

**Comment by dlongley** [comment]
Related to #12

**Comment by DRK3** [comment]
Thanks for the heads up!

**Comment by DRK3** [comment]
Since this issue is already cross-referenced in #12, this issue can be closed now.
